### ISSUE TITLE
ajax list filters - 403 forbidden

### ISSUE THREAD

**Issue by papagandalf** [chrisspen/django-admin-steroids#8]
Hello,
I am trying to use the Ajax list filters - good job on that btw, I've been searching for something like this for a long time!
I've followed the instructions and for some reason, the search request gets 403 response. Is there anything else I should configure? I've seen that this is usually related to the CSRF token.

**Comment by chrisspen** [comment]
That's not much to go on. What Django version are you using? Check your auth.user permissions.

**Comment by papagandalf** [comment]
I found out what was the problem. In the settings file, in DAS_ALLOWED_AJAX_SEARCH_PATHS, where I defined ('myapp', 'mymodel', 'myfield'), I was using the model's name as is. When I wrote the model name with lowercase letters only, it worked.
